### ISSUE TITLE
Validate town names

### ISSUE THREAD

**Issue by joelabrams** [BostonGlobe/11-04-2014-elections#43]
http://devedit.bostonglobe.com/news/politics/election-results/town/MA/Fuck-the-Boston-Globe
![screen shot 2014-10-29 at 1 26 30 pm](https://cloud.githubusercontent.com/assets/622091/4830874/be80faae-5f90-11e4-9b17-7b1fe99d6579.png)

**Comment by gabrielflorit** [comment]
the JPT should do this validation (Arnstein)
