### ISSUE TITLE
Things with spaces that still break

### ISSUE THREAD

**Issue by joelabrams** [BostonGlobe/11-04-2014-elections#45]
Towns:
http://devedit.bostonglobe.com/news/politics/election-results/town/NH/East%20Kingston
Offices:
http://devedit.bostonglobe.com/news/politics/election-results/race/MA/U.S.%20House/District%202
http://devedit.bostonglobe.com/news/politics/election-results/race/MA/State%20Senate/Plymouth%20&%20Norfolk

Ballot questions:
http://devedit.bostonglobe.com/news/politics/election-results/race/MA/Question/5%20-%2010Ply%202%20Part%20Question

**Comment by gabrielflorit** [comment]
FIXED: http://devedit.bostonglobe.com/news/politics/election-results/race/MA/Question/5%20-%2010Ply%202%20Part%20Question

**Comment by gabrielflorit** [comment]
also, http://devedit.bostonglobe.com/news/politics/election-results/race/MA/State%20Senate takes you to the wrong page atm

**Comment by gabrielflorit** [comment]
we need to test every single 2014-11-04 race

**Comment by gabrielflorit** [comment]
@joelabrams can you please test every thing? try clicking as much as possible on this page, i think i fixed all the "things with spaces still break" errors

**Comment by joelabrams** [comment]
http://devedit.bostonglobe.com/news/politics/election-results/2014-11-04/race/MA/Attorney%20General/ has no data on it - I reached it from the office page

No data on http://devedit.bostonglobe.com/news/politics/election-results/2014-11-04/race/NH/Governor/

No data on http://devedit.bostonglobe.com/news/politics/election-results/2014-11-04/race/MA/Governor%E2%80%99s%20Council/District%201
http://devedit.bostonglobe.com/news/politics/election-results/2014-11-04/race/MA/Governor%E2%80%99s%20Council/District%208

I think I tested at least one instance of every type
