### ISSUE TITLE
two "updating in xx seconds" at top of sidebar results jpt on homepage

### ISSUE THREAD

**Issue by joelabrams** [BostonGlobe/11-04-2014-elections#93]
![screen shot 2014-11-04 at 5 01 40 am](https://cloud.githubusercontent.com/assets/622091/4903087/00e59768-643e-11e4-8d10-9e0491fc8a07.png)

The first one does not update; the second one does.

**Comment by gabrielflorit** [comment]
that's due to producers entering wrong race numbers in jpt
